repos:
  # Python hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Increase size limit to 10MB
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
        files: ^(src|scripts|migrations)/.*\.py$|^main\.py$

  # Black formatter disabled - using ruff format instead
  # - repo: https://github.com/psf/black
  #   rev: 24.1.1
  #   hooks:
  #     - id: black
  #       language_version: python3.12
  #       files: ^(src|scripts|migrations)/.*\.py$|^main\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src|scripts|migrations)/.*\.py$|^main\.py$
      - id: ruff-format
        args: [--check]
        files: ^(src|scripts|migrations)/.*\.py$|^main\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1  # Match the version in pyproject.toml
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies: [
          types-python-dateutil,
          types-requests,
          sqlalchemy-stubs,
          types-PyYAML,
          pytest,
          pytest-asyncio,
          pydantic,
          pydantic-settings,
          fastapi,
          uvicorn,
          httpx,
          boto3-stubs,
          reportlab,
          types-tabulate,
          types-colorama
        ]
        files: ^(src|scripts)/.*\.py$|^main\.py$  # Exclude migrations as per pyproject.toml
        args: [
          --config-file=pyproject.toml,  # Use project's mypy configuration
          --show-error-codes,
          --pretty
        ]
